language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# gradlew 에 권한 부여
before_install:
  - chmod +x gradlew

# S3에 올리기

# jar 파일 압축
before_deploy:
  - zip -r naldal-springboot2-webservice *
  - mkdir -p deploy # deploy 라는 디렉토리를 Travis CI가 실행중인 위치에서 생성
  - mv naldal-springboot2-webservice.zip deploy/naldal-springboot2-webservice.zip

# 외부 서비스와 연동될 행위를 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings 에 설정된 값
    bucket: naldal-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 으로
    local_dir: deploy # before_deploy 에서 생성한 디렉토리. 이 위치의 파일들만 S3로 전송
    wait-until-deployed: true성


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - "cec7777@naver.com"